<<TayIntfunctions.m
<<TayInt.m
SetDirectory["D6"]
epsord=E1;
{name=N1;}
{(CAdomsec[#]=Import[ToString[name]<>ToString[epsord]<>"CAdomsec"<>ToString[#]<>".txt"])&/@Range[1,Length[SecList]]}
varlist=Import[ToString[name]<>ToString[epsord]<>"varlist.txt"]
SecList=Import[ToString[name]<>ToString[epsord]<>"SecList.txt"]
CAdomsecSub=Import[ToString[name]<>ToString[epsord]<>"CAdomsecSub.txt"]
{(PartSubFinal[#]=Import[ToString[name]<>ToString[epsord]<>"PartSubFinal"<>ToString[#]<>".txt"])&/@Range[1,Length[SecList]]}
{SubVarFinalTab=Import[ToString[name]<>ToString[epsord]<>"SubVarFinalTab.txt"]}
{(CCFinal[#]=Import[ToString[name]<>ToString[epsord]<>"CCFinal"<>ToString[#]<>".txt"])&/@Range[1,Length[SecList]]}
{CCNIELcalc=Import[ToString[name]<>ToString[epsord]<>"CCNIELcalc.txt"]}
{RatKMSE=Import[ToString[name]<>ToString[epsord]<>"RatKMSE.txt"]}
{CCNIELpartialcalc=Import[ToString[name]<>ToString[epsord]<>"CCNIELpartialcalc.txt"]}
{(PartContFinal[#]=Import[ToString[name]<>ToString[epsord]<>"PartContFinal"<>ToString[#]<>".txt"])&/@Range[1,Length[SecList]]}
{kinenames=Import[ToString[name]<>ToString[epsord]<>"kinenames.txt"]}
{ResKine=Import[ToString[name]<>ToString[epsord]<>"ResKine.txt"]}
{KineList=Import[ToString[name]<>ToString[epsord]<>"KineList.txt"]}
{GoodListSecKine=Import[ToString[name]<>ToString[epsord]<>"GoodListSecKine.txt"]}
SetDirectory["D3"]
{COMPDiscTaySeriesIntegrator[CAdomsec[#],varlist,varlist,0,4,(ToString[name]<>"OTEPS"<>ToString[epsord]),#]&/@Range[S2,S2]}
{If[Length[GoodListSecKine[[#]]]<Round[Length[KineList]/2],COMPDiscTaySeriesIntegrator[CAdomsecSub[[#]][[PartSubFinal[#]]],SubVarFinalTab[[PartSubFinal[#]]],SubVarFinalTab[[PartSubFinal[#]]],0,4,(ToString[name]<>"OTEPS"<>ToString[epsord]),#]]&/@Range[S2,S2]}
{COMPDiscTaySliceOutput[#,(ToString[name]<>"OTEPS"<>ToString[epsord]),varlist,varlist,0,4,CCNIELcalc[[CCFinal[#]]],RatKMSE[[#]]]&/@Range[S2,S2]}
{If[Length[GoodListSecKine[[#]]]<Round[Length[KineList]/2],COMPDiscTaySliceOutput[#,(ToString[name]<>"OTEPS"<>ToString[epsord]),SubVarFinalTab[[PartSubFinal[#]]],SubVarFinalTab[[PartSubFinal[#]]],0,4,CCNIELpartialcalc[[PartSubFinal[#]]][[PartContFinal[#]]],RatKMSE[[#]]]]&/@Range[S2,S2]}
{Table[COMPKineTABTABFlexVarIndFast3ThWheelB[i,(ToString[name]<>"OTEPS"<>ToString[epsord]),varlist,varlist,0,4,CCNIELcalc[[CCFinal[i]]],RatKMSE[[i]],kinenames,ResKine[[#]],#],{i,S2,S2}]&/@Range[1,Length[ResKine]]}
{Table[If[Length[GoodListSecKine[[i]]]<Round[Length[KineList]/2],COMPKineTABTABFlexVarIndFast3ThWheelB[i,(ToString[name]<>"OTEPS"<>ToString[epsord]),SubVarFinalTab[[PartSubFinal[#]]],SubVarFinalTab[[PartSubFinal[#]]],0,4,CCNIELpartialcalc[[PartSubFinal[#]]][[PartContFinal[#]]],RatKMSE[[i]],kinenames,ResKine[[#]],#]],{i,S2,S2}]&/@Range[1,Length[ResKine]]}
(*now we test the results for dud patches*)
{(TayIntResDiff[#]=Table[Abs[TayIntRes[#][[i+1]]/TayIntRes[#][[i]]],{i,1,Length[TayIntRes[#]]-1}])&/@Range[S2,S2]}
{(TayIntResDudPos[#]=Flatten[Table[If[TayIntResDiff[#][[i]]>1.1||TayIntResDiff[#][[i]]<0.9,Position[TayIntResDiff[#],TayIntResDiff[#][[i]]]+1],{i,1,Length[TayIntRes[#]]-1}]/.{Null->Nothing}])&/@Range[S2,S2]}
{(MinTayIntResDudPos[#]=Min[TayIntResDudPos[#]])&/@Range[S2,S2]}
{(MaxTayIntResDudPos[#]=Max[TayIntResDudPos[#]])&/@Range[S2,S2]}
{RatDud=ConstantArray[ConstantArray[1,(Round[Length[varlist]/2]+1)],Length[varlist]]}
{If[Length[TayIntResDudPos]>0,COMPDiscTaySliceOutput[1,#,(ToString[name]<>"OTEPS"<>ToString[epsord]),varlist,varlist,0,4,CCNIELcalc[[CCFinal[#]]],RatDud]]&/@Range[S2,S2]}
{If[Length[GoodListSecKine[[#]]]<Round[Length[KineList]/2],If[Length[TayIntResDudPos]>0,COMPDiscTaySliceOutput[1,#,(ToString[name]<>"OTEPS"<>ToString[epsord]),SubVarFinalTab[[PartSubFinal[#]]],SubVarFinalTab[[PartSubFinal[#]]],0,4,CCNIELpartialcalc[[PartSubFinal[#]]][[PartContFinal[#]]],RatDud]]]&/@Range[S2,S2]}
If[Length[TayIntResDudPos]>0,Table[TayIntRes[i]=COMPKineTABTABFlexVarIndFast3ThWheelB[i,i,(ToString[name]<>"OTEPS"<>ToString[epsord]),varlist,varlist,0,4,CCNIELcalc[[CCFinal[i]]],RatDud,kinenames,ResKine[[#]],#]&/@Range[MinTayIntResDudPos[i]-3,MaxTayIntResDudPos[i]+3],{i,S2,S2}]]
{Table[If[Length[GoodListSecKine[[i]]]<Round[Length[KineList]/2],If[Length[TayIntResDudPos]>0,TayIntRes[i]=COMPKineTABTABFlexVarIndFast3ThWheelB[i,i,(ToString[name]<>"OTEPS"<>ToString[epsord]),SubVarFinalTab[[PartSubFinal[#]]],SubVarFinalTab[[PartSubFinal[#]]],0,4,CCNIELpartialcalc[[PartSubFinal[#]]][[PartContFinal[#]]],RatDud,kinenames,ResKine[[#]],#]]]&/@Range[MinTayIntResDudPos[i]-3,MaxTayIntResDudPos[i]+3],{i,S2,S2}]}
